site_name: HPC Administrators Handbook
site_url: https://hpcbook.io
dev_addr: localhost:9000

theme:
  name: material
  palette:
    primary: "blue grey"
  features:
    - navigation.indexes
    - content.code.annotate 

nav:
  - Home: index.md
  - Introduction:
    - introduction/index.md
    - History: introduction/history.md
    - How To: introduction/howto.md
  - Hardware:
    - hardware/index.md
    - Processors: hardware/processors.md
    - Accelerators: hardware/accelerators.md
    - Motherboard: hardware/motherboard.md
    - Storage: hardware/storage.md
    - Racks: hardware/racks.md
    - Power: hardware/power.md
    - Cooling: hardware/cooling.md
    - Bottlenecks: hardware/bottlenecks.md
    - Network Cables: hardware/network_cabling.md
    - Composable Infrastructure: hardware/composable.md
  - Networking:
    - networking/index.md
    - Topologies: networking/topologies.md
    - Interconnects: networking/interconnects.md
    - DNS: networking/dns.md
    - Bonding: networking/bonding.md
  - Storage:
    - storage/index.md
    - Filesystems: storage/filesystems.md
    - Multipath: storage/multipath.md
    - Parallel Filesystems: storage/parallel_filesystems.md
    - Scratch: storage/scratch.md
    - Quoata Management: storage/quotas.md
  - Provisioning:
    - provisioning/index.md
    - Warewulf: provisioning/warewulf.md
    - Grendel: provisioning/grendel.md
    - Cobbler: provisioning/cobbler.md
    - XCat: provisioning/xcat.md
  - Cloud:
    - cloud/index.md
    - AWS: cloud/aws.md
    - Azure: cloud/azure.md
  - Job Scheduling:
    - schedulers/index.md
    - Slurm: schedulers/slurm.md
    - OpenTorque: schedulers/torque.md
    - OpenLava: schedulers/openlava.md
    - HTCondor: schedulers/htcondor.md
    - Kubernetes: schedulers/k8s.md
    - Munge: schedulers/munge.md
  - Applications:
    - apps/index.md
    - Helper Tools: apps/helpers.md
    - Cuda: apps/cuda.md
    - Anaconda: apps/conda.md
    - Containers: apps/containers.md
    - Modules: apps/modules.md
    - MPI: apps/mpi.md
    - OpenMP: apps/openmp.md
  - Benchmarking:
    - benchmark/index.md
    - CPU: benchmark/cpu.md
    - MPI: benchmark/mpi.md
    - Storage: benchmark/storage.md
    - GPU: benchmark/gpu.md
    - Top Lists: benchmark/top.md
  - Devops:
    - devops/index.md
  - Monitoring: 
    - monitoring/index.md
    - Databases: monitoring/databases.md
    - Collectors: monitoring/collectors.md
    - Node Health Check: monitoring/nhc.md
    - Dashboards: monitoring/dashboards.md
  - Acceptance Testing:
    - acceptance/index.md
  - Documentation: documentation.md
  - References: references.md

markdown_extensions:
  - admonition
  - abbr
  - footnotes
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets:
      auto_append:
        - includes/glossary.md
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - tables

plugins:
  - search
